# Generated by Django 5.0 on 2024-09-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_bangladesh_entertainment_politics_sports_technology_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='latest',
            new_name='latest_news',
        ),
    ]
