# Generated by Django 5.0 on 2024-09-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_latest_latest_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bangladesh',
        ),
        migrations.DeleteModel(
            name='entertainment',
        ),
        migrations.DeleteModel(
            name='politics',
        ),
        migrations.DeleteModel(
            name='sports',
        ),
        migrations.DeleteModel(
            name='technology',
        ),
        migrations.DeleteModel(
            name='trade',
        ),
        migrations.DeleteModel(
            name='world',
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='image',
            field=models.ImageField(upload_to='news_images/'),
        ),
    ]
