# Generated by Django 5.0 on 2024-09-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_bangladesh'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangladesh',
            name='subtitle',
            field=models.CharField(default='Default Subtitle', max_length=400),
        ),
        migrations.AddField(
            model_name='latest_news',
            name='subtitle',
            field=models.CharField(default='Default Subtitle', max_length=400),
        ),
    ]
