# Generated by Django 5.0 on 2024-09-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_bangladesh_subtitle_latest_news_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangladesh',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='latest_news',
            name='subtitle',
        ),
    ]
