# Generated by Django 5.0 on 2024-09-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_bangladesh_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangladesh',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
