# Generated by Django 5.0 on 2024-09-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_politics_sec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='latest_news',
            new_name='BangladeshNews',
        ),
        migrations.RenameModel(
            old_name='bangladesh',
            new_name='LatestNews',
        ),
        migrations.RenameModel(
            old_name='politics_sec',
            new_name='PoliticsNews',
        ),
    ]
